<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sandbox.services</groupId>
        <artifactId>sandbox-common</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>sandbox-common-base</artifactId>
    <version>${revision}</version>
    <name>sandbox-common-base</name>
    <description>基础公共模块</description>

    <dependencies>

        <!-- 通用工具类 Begin -->
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
        </dependency>
        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
        </dependency>
        <!-- 通用工具类 End -->

    </dependencies>
</project>
