apiVersion: v1
kind: Secret
metadata:
  name: deepseek-credentials
  namespace: default
type: Opaque
data:
  # base64 编码的 API Key
  # 可以用命令生成：echo -n "sk-cc3500c1b40b4e14b73d2d120d06881c" | base64
  api-key: c2stY2MzNTAwYzFiNDBiNGUxNGI3M2QyZDEyMGQwNjg4MWM=