server:
  port: 1012
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  web:
    resources:
      add-mappings: false # 禁用默认的静态资源映射
  application:
    name: sandbox-mcp-server

  ai:
    mcp:
      server:
        name: sandbox-mcp-server
        version: 1.0.0
        type: sync
        sse-message-endpoint: /mcp/message