spring:
  config:
    activate:
      # 指定当前生效的配置文件
      on-profile: dev
    #显式导入外部配置 Nacos
    import:
      - optional:nacos:${spring.application.name}-${spring.config.activate.on-profile}.${spring.cloud.nacos.config.file-extension}

  cloud:
    nacos:
      config:
        # Nacos 服务器地址
        server-addr: localhost:8848
        # 命名空间 ID（可选）
        namespace: 276b89aa-db62-47ef-b05a-6f14fdd23da2
        # 配置分组（默认 DEFAULT_GROUP）
        group: DEFAULT_GROUP
        # 配置格式（yaml 或 properties）
        file-extension: yaml
        # 启用动态刷新
        refresh-enabled: true
        username: nacos
        password: nacos

      discovery:
        server-addr: localhost:8848
        namespace: 276b89aa-db62-47ef-b05a-6f14fdd23da2
        username: nacos
        password: nacos

  ai:
    openai:
      api-key: sk-d6d53007e0ac4279ac991f2fc777c721
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
      embedding:
        api-key: sk-igytzpxsqvvzgytmunbeshyrdirznvpflvwlxcngkiolzuki  # SiliconFlow 的 key
        base-url: https://api.siliconflow.cn  # 注意路径必须是完整端点
        options:
          model: netease-youdao/bce-embedding-base_v1
    mcp:
      client:
        enabled: true
        name: sandbox-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: sync
        sse:
          connections:
            server1:
              url: http://localhost:1012

# 日志打印级别
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

business-config:
  prompts:
    user-talk: "你是一个友好的AI助手，请用中文回答用户的问题"